### ISSUE TITLE
not loading player

### ISSUE THREAD

**Issue by Makaros1** [ThScEo/ForgeOfBot#15]
i tried to log my main player who has many buildings and a little big city ...passed the login window and server selection but nothing was loaded...
![image](https://user-images.githubusercontent.com/49597451/104457084-3b28c780-55b2-11eb-9e33-bcaf8c3a472c.png)

**Comment by ThScEo** [comment]
Please, report several informations about your issue, like mentionned [here](https://github.com/ThScEo/ForgeOfBot/blob/master/README.md) : 

- Which OS you run
- What is your server
- Have you tried to reproduce the issue with another account?

**Comment by makarosVar** [comment]
my OS is WIN10 (64bit) , i am in gr server ,
 i have created another account in the same server and region and work just fine...
 i believe it's because in my main account has a lot to process and i currently am in colonial age and i have a little big city...
 Also i noticed that the app cannot save the player's name when written in greek , so it is that as well.

**Comment by ThScEo** [comment]
- Yes, the issue about save player's name with greek chars happen due to different charset. That should not be hard to fix.
- The other issue is maybe due to the metadata used by the soft. I will do some researches about that
